name: CI

on:
  push:
    branches: [master]
    paths:
      - "**.zig"
  pull_request:
    branches: [master]
    paths:
      - "**.zig"
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      - name: Check environment
        run: |
          zig env
